// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tguztpestoypsdrqyqin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRndXp0cGVzdG95cHNkcnF5cWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzE4ODQsImV4cCI6MjA3MjMwNzg4NH0.eN8BoITin-pvv0Xuj1HJGUYsNvhkvmp4x_j56BN_TCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});